### ISSUE TITLE
Inconsistent issue with filesystem access in the Docker self-hosted bot

### ISSUE THREAD

**Issue by auctumnus** [esmBot/esmBot#227]
### Describe the bug

For some commands and some runs the bot seems to be lacking permission to read intermediate images generated, or other files in general? This is a really inconsistent issue and I've only gotten two errors from it so far, having run this for like maybe 15 minutes, but I'll update the issue if more come in over time.

Logs below:
```
bot_1       | [2022-01-28 21:06:23]: [ERROR] - Cluster 0 | Unhandled Rejection at: Promise {
bot_1       |   <rejected> [Error: EACCES: permission denied, open '/home/esmBot/help/help.md'] {
bot_1       |     errno: -13,
bot_1       |     code: 'EACCES',
bot_1       |     syscall: 'open',
bot_1       |     path: '/home/esmBot/help/help.md'
bot_1       |   }
bot_1       | } reason: Error: EACCES: permission denied, open '/home/esmBot/help/help.md'
...
bot_1       | [2022-01-28 22:25:54]: [MAIN] - Cluster 0 | [USER] ([ID]) ran command haah
bot_1       | [2022-01-28 22:26:20]: [ERROR] - Cluster 0 | Error occurred with command message s&haah: Error: EACCES: permission denied, open '/home/esmBot/temp/6376igpemwe.gif'
```

The same command worked for other images/users, though. Not sure why.

### Steps to reproduce

1. Run the bot through Docker
2. Use a command, presumably one that requires an intermediate file read/write
3. See error

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
Try 72c3d67, it changes the Dockerfile to create the directories and set permissions (you will need to rebuild the container).

**Comment by auctumnus** [comment]
You forgot to add `RUN` before those commands, lol. I've made a PR at #228 for that quick fix.
Still getting the issue as far as the /help/help.md bit - I attached a bash session as root to the running container and the file doesn't appear to exist?
![image](https://user-images.githubusercontent.com/37276280/151682325-7d3c848d-0af6-4f0a-9836-5586dffcda49.png)
No issues yet with the temporary intermediate files, anyway.

**Comment by auctumnus** [comment]
Nope, still getting the issue. Same error message as earlier with `&haah`. I don't know the structure of esmbot, but my only guess would be if there's like, maybe a race condition between reading a temp file and deleting it?

**Comment by TheEssem** [comment]
The bot itself doesn't read any files in the directory, it only writes.

Might I ask what the permissions of your `bot-temp` and `bot-help` directories on the host are?

**Comment by auctumnus** [comment]
They're owned by `root`. I honestly didn't notice that they were even a separate directory on the host? I had kinda assumed they'd be in the container itself.
Anyway, I deleted them and rebuilt the container, and it still shows them as being owned by `root`.

**Comment by TheEssem** [comment]
That's... interesting. What about the read/write/executable bits?

**Comment by auctumnus** [comment]
```
drwxr-xr-x   2 root   root     4096 Jan 30 01:05 bot-help
drwxr-xr-x   2 root   root     4096 Jan 30 01:05 bot-temp
```

**Comment by TheEssem** [comment]
Try that, yeah. It seems that the permissions I originally specified were unsuitable anyways; I just pushed another commit to try and fix that.

**Comment by auctumnus** [comment]
Still inexplicably getting the problem at least for `help.md`. The permissions of the folders don't appear to actually be getting changed? I ran `chmod 666` as the Dockerfile specifies on `bot-help`, but not `bot-temp`, and the permissions ended up like
```
drw-rw-rw-  2 root   root     4096 Jan 30 22:32 bot-help
drwxr-xr-x  2 root   root     4096 Jan 30 22:32 bot-temp
```
In any case, it doesn't appear to have helped - even with `bot-help` set to `666` it's still encountering the issue.
I'd be interested to see if you / anyone else can reproduce it? I'd be happy with "this is an inexplicable hell situation specific to my setup" as an answer and just `chmod 777` it.

**Comment by DracoMilesX** [comment]
Was trying to get the bot up and running in docker myself and ran into the same issue.
Setting permissions to '666' doesn't work, setting permissions to '777' did work.

Doing 'chown -R esmBot:esmBot help/' inside the docker container works or 'chown -R 1001:1001 bot-help/' on the host works too for me with the default permissions.
